name: flutter test
run-name: ${{ github.actor }} is testing flutter code
on: [push]
jobs:
  flutter_obj_test: 
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v1
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: "flutter pub get"
      - name: "Run Flutter Obj Tests"
        run: "flutter test test/obj_test.dart"
