name: flutter test
run-name: ${{ github.actor }} is testing flutter code
on: [push]
jobs:
  flutter_obj_test: 
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.11'
      - name: flutter upgrade
        run: flutter upgrade
      - name: get dependencies
        run: "flutter pub get"
      - name: "Run Flutter Obj Tests"
        run: "flutter test test/obj_test.dart"
